export const FETCHING_PRODUCT_CATEGORIES = "FETCHING_PRODUCT_CATEGORIES";
export const FETCHING_PRODUCT_CATEGORIES_FAILURE = "FETCHING_PRODUCT_CATEGORIES_FAILURE";
export const FETCHING_PRODUCT_CATEGORIES_SUCCESS = "FETCHING_PRODUCT_CATEGORIES_SUCCESS";